#!/bin/bash

# Programme de copie de fichier TIFF qui marche avec le format ROK PNG
# Hypothese: Fichier 4096*4096 tuiles 256*256 compression AdobeDeflate

set +x

result="`tiffinfo $4`"
isFormatRok4Png="`echo $result | grep "Compression Scheme: AdobeDeflate" | grep "Image Width: 4096 Image Length: 4096" | grep "Tile Width: 256 Tile Length: 256" `"

if [ -z "$isFormatRok4Png" ] ; then
	tiffcp $*
else
	Programeafaire $*;
fi;

