message(STATUS "Building a rpm package")

set(CPACK_RPM_PACKAGE_VENDOR "IGN")

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
else()
  set(CPACK_RPM_PACKAGE_ARCHITECTURE "i686")
endif()

set(CPACK_BINARY_RPM "ON")
set(CPACK_GENERATOR "RPM")
